function [em_hydro_offset, nrg_hydro_offset] = hydroOffset(x_other, ...
        em_transition_transport, em_transition_embodied, em_drying, em_otherInputs_transport, em_otherInputs_embodied,...
        em_Li2CO3_transport, em_Li2CO3_embodied, nrg_transition_transport, nrg_transition_embodied, ...
        nrg_drying, nrg_otherInputs_transport, nrg_otherInputs_embodied, ...
        nrg_Li2CO3_transport, nrg_Li2CO3_embodied)

li_percent = getLiPercent; 
    
em_hydro_offset = em_transition_embodied + ...
    em_otherInputs_embodied +  ...
    li_percent*(em_Li2CO3_transport + em_Li2CO3_embodied); 
nrg_hydro_offset = nrg_transition_embodied + ...
    nrg_otherInputs_embodied + ...
    li_percent* (nrg_Li2CO3_transport + nrg_Li2CO3_embodied);